wandb_version: 1

_wandb:
  desc: null
  value:
    bounding_box/class_labels:
      BoundingBoxDebugger_wandb_delimeter_predictions:
        key: BoundingBoxDebugger_wandb_delimeter_predictions
        type: bounding_box/class_labels
        value:
          '0': Bike
          '1': E-scooter
          '2': Pedestrian
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1674144324.211903
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      2:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.13.6
      8:
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 24
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: /mnt/gpid07/imatge/miriam.elbaz/workspace/yolov5/models/yolov5l.yaml
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: people_data.yaml
data_dict:
  desc: null
  value:
    names:
      '0': Bike
      '1': E-scooter
      '2': Pedestrian
    nc: 3
    path: /mnt/gpid07/imatge/miriam.elbaz/workspace/yolov5
    test: /home/usuaris/imatge/miriam.elbaz/workspace/Dataset/images/test
    train: /home/usuaris/imatge/miriam.elbaz/workspace/Dataset/images/train
    val: /home/usuaris/imatge/miriam.elbaz/workspace/Dataset/images/val
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 150
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.3
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.1
    mixup: 0.1
    momentum: 0.937
    mosaic: 1.0
    obj: 0.7
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.9
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: people_det
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: yolov5/runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: yolov5/runs/train/people_det26
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5m.pt
workers:
  desc: null
  value: 4
